# Generated by Django 3.1.1 on 2020-11-26 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faircare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedurePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_price', models.CharField(max_length=200)),
                ('procedure_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_price', to='faircare.procedure')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_state', to='faircare.state')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200)),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_price', to='faircare.medication')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_state', to='faircare.state')),
            ],
        ),
    ]
